name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: npm install pnpm --global
      - run: pnpm install
      - run: pnpm build
